export {
  createVideoProject,
  defaultGenerationSettings,
  defaultRiskFlags,
  formatStrategyInputSchema,
  formatTypes,
  generationSettingsSchema,
  ideaInputSchema,
  normalizeFormatStrategy,
  projectInputSchema,
  syncPriorities,
  videoStatuses,
} from '../../server/project-schema.mjs'

export type {
  FormatStrategy,
  FormatStrategyInput,
  FormatType,
  GenerationSettings,
  Idea,
  IdeaInput,
  Narration,
  RenderResult,
  ReviewChecklist,
  RiskFlags,
  ScenePlan,
  ScenePlanScene,
  SourceBundle,
  Storyboard,
  SyncPriority,
  Thumbnail,
  VideoProject,
  VideoStatus,
} from '../../server/project-schema.mjs'
